# -*- coding: utf-8 -*-
"""TesteFFTs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LRrZq0NMkij2P3Zfm20ZmmXzvBT7Iar2
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import signal

# Simular dados de vibração de máquina
fs = 1000  # Frequência de amostragem (Hz)
t = np.arange(0, 1, 1/fs)
f1, f2 = 50, 120  # Frequências características (Hz)
vibracao = 1.5*np.sin(2*np.pi*f1*t) + 0.8*np.sin(2*np.pi*f2*t) + 0.5*np.random.randn(len(t))

# Análise no domínio da frequência
frequencias, espectro = signal.welch(vibracao, fs, nperseg=1024)

# Plot
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(t[:200], vibracao[:200])
plt.title('Sinal de Vibração (Domínio do Tempo)')
plt.xlabel('Tempo [s]')
plt.ylabel('Amplitude')

plt.subplot(1, 2, 2)
plt.semilogy(frequencias, espectro)
plt.title('Espectro de Frequência')
plt.xlabel('Frequência [Hz]')
plt.ylabel('Densidade Espectral')
plt.tight_layout()
plt.show()